### ISSUE TITLE
[ESTAGIO] [SALVADOR] Processo Seletivo de Bolsista para a STI na [UFBA]

### ISSUE THREAD

**Issue by lizvidotti91** [devssa/onde-codar-em-salvador#1114]
## Descrição da vaga

- A Superintendência de Tecnologia da Informação (STI) da UFBA está selecionando estagiários para atuar nas seguintes vagas: Núcleo de Editoração de Home Page, Gerência de Eventos, Apoio ao Usuário, Qualidade e Teste de Software, Desenvolvimento de Software, Análise de Negócio, Arquivologia, Moodle, Desenvolvimento de Soluções de Integração para Infraestrutura, Gestão de Processos e Qualidade, Licitações e Contratos, Segurança da Informação
- Horário compatível com os estudos
- Acelere o seu crescimento profissional

## Local

- Salvador 

## Benefícios

- Bolsa remunerada
- Horário Flexível
- Ótimo ambiente de trabalho
- Oportunidade de crescimento
- Treinamentos

## Contratação

- a combinar

## Nossa empresa

- A Superintendência de Tecnologia da Informação (STI) é o órgão estratégico da Universidade Federal da Bahia para o planejamento das ações e políticas da área da informática. Para o cumprimento das suas atribuições são compostas 5 coordenações, conforme organograma aprovado no regimento da UFBA. As atribuições específicas são descritas detalhadamente, no âmbito de cada coordenação.
 - A STI é dirigida desde maio de 2013 por Luiz Cláudio Araújo Mendonça.
 - As atribuições da STI são definidas em regimento aprovado pelo Conselho Universitário em maio de 2013.

## Como se candidatar

- Faça a sua inscrição ATÉ 22/11/2020 no site www.sti.ufba.br

**Comment by murillomtz** [comment]
Ele pede numero de matricula, precisa ser aluno da UFBA?

**Comment by lizvidotti91** [comment]
Olá, @murillomtz! Eu não sei te informar... é melhor você entrar em contato com eles
