### ISSUE TITLE
[JAVASCRIPT] [PHP][MYSQL] Desenvolvedor Front-End  ou Back-End na [VXCASE]

### ISSUE THREAD

**Issue by cilas** [devssa/onde-codar-em-salvador#1205]
## Descrição da vaga

    Vagas para Pleno ou Sênior, mas aceitamos inscrição de pessoas de nível junior.
    Stack: Javascript ES6+, PHP, Docker e bancos de dados relacionais e não relacionais
    40 horas semanais
    Para se candidatar, não é necessário possuir nenhum título acadêmico, como Mestrado ou Doutorado

## Local

- Salvador - BA (presencial)

## Benefícios

    Vale Alimentação
    Vale Transporte
    Assistência Médica
    Assistência Odontológica
    Ambiente colaborativo
    Flexibilidade de horário
    Sala de Descompressão feita pra quem precisa relaxar e descansar um pouco. Com fliperama e PS
    Não temos Dress Code. Você pode vir vestido como quiser (respeitando sempre o outro)
    Plano de Carreira

## Requisitos

**Obrigatórios:**
  BACK-END:
        Experiência em Laravel
        Experiência fazendo APIs
        Experiência com Docker (básico)
        Experiência com bancos de dados relacionais (mySQL)
        Conhecimento em versionamento com Git
    FRONT-END:
        Conhecimento em Javascript ES6+
        Conhecimento em Angular, React ou VUE
        Proficiência em HTML, CSS e Javascript (ES6+)
        Conhecimento em versionamento com Git
        Experiência de Usuário (UX / UI)

**Diferenciais:**
    Experiência em Angular
    Experiência com NoSQL
    Apresentação de portfólio, GitHub ou similares
    Experiência com Notas Fiscais Eletrônicas
    Conhecimento em VTex

## Contratação
     CLT - Efetivo, PJ
      a combinar
## Nossa empresa

- [vxcase.com.br](vxcase.com.br)

## Como se candidatar

- Por favor envie um email para  jamillysantana@vxcase.com.br com seu CV anexado - enviar no assunto: Desenvolvedor Front-End ou Back-End

**Comment by devXela** [comment]
Fechada?

Att,

Alex Rosa Santos Barbosa
Desenvolvedor WEB

PHP5 - MySQL - jQuery


Em dom., 22 de jan. de 2023 às 21:33, github-actions[bot] <
***@***.***> escreveu:
