### ISSUE TITLE
[FRONTEND] [REACT] [REMOTO] Desenvolvedor Front-End React.JS na [MUNDIALE]

### ISSUE THREAD

**Issue by lizvidotti91** [devssa/onde-codar-em-salvador#1249]
## Descrição da vaga

- ⚡ Aqui na Mundiale, você terá espaço para trabalhar em grandes e desafiadores projetos, com tecnologias de ponta, as versões mais atualizadas, práticas de desenvolvimento ágil, microsserviços, soluções focadas em promover a melhor experiência do cliente e com infraestrutura tecnológica de última geração.
- Se identificou? Então, que tal integrar suas forças ao nosso time?
- Buscamos uma pessoa com experiência em desenvolvimento front-end para se juntar a nossa equipe que será responsável pelo desenvolvimento do “lado cliente” (client-side) de websites, landing pages, hotsites, blogs e aplicações web da nossa empresa.
- Para isso, precisamos que você seja capaz de traduzir as necessidades e funcionalidades em plataformas funcionais e atraentes

## Local

- Remoto

## Benefícios

- Benefício Flexível (você define como utilizar de acordo com suas necessidades: cultura, app de transporte, assinaturas, academia, alimentação, etc)
- Plano de Saúde Unimed (Unipart);
- Plano Odontológico Odontoprev;
- Programa de Trainee;
- Trilha de carreira;
- Ambiente de trabalho colaborativo e dinâmico.

## Requisitos

**Obrigatórios:**
- ReactJS, React Native, Redux, Flux
- HTML, SASS e CSS
- Integração com serviços
- Compatibilidade entre navegadores e layout responsivo

## Contratação

- a combinar

## Nossa empresa

- A Mundiale tem como foco proporcionar a melhor experiência para os seus clientes, cuidando de cada etapa da jornada de compra. O objetivo é ser touch num mundo tech, conectando todos os pontos de interação do cliente com a sua marca, através de tecnologias que facilitam a vida das pessoas proporcionam comodidade, agilidade, economia de tempo, atendimento excelente e confiança.
- Para isso, possui uma grande estrutura focada em desenvolvimento, para criação de tecnologias e canais que proporcionem a melhor experiência de atendimento e compra para o cliente; em marketing digital para geração de fluxo e conversão; em pessoas, metodologias e equipamentos, para fornecer o melhor atendimento; e em planejamento e análise de dados, para garantir resultados impactantes.
- Desenvolve soluções que possibilitam transações de vendas por todos os canais e meios digitais, do telefone ao atendimento feito por robôs em chats, Facebook e Whatsapp.
- Grandes operadoras de telefonia, bancos, posto de combustível, seguradoras e empresas de telecom, escolheram a Mundiale pelo seu compromisso com a valorização de gente, com a inovação e os resultados.

## Como se candidatar

- [Clique aqui para se candidatar](https://jobs.kenoby.com/mundiale/job/frontend-developer-react-js/5f8eef5dec53152a51d6ec8e?utm_source=website)

**Comment by joao160197** [comment]
Não estou conseguindo me candidatar pelo site teria outro maneira de fazer a candidatura

**Comment by BrendaCosta** [comment]
Oi @joao160197 , a vaga ja ta fechada...

**Comment by joao160197** [comment]
Ok
