### ISSUE TITLE
[REMOTO] [SÊNIOR] [PYTHON] [DJANGO] [CELERY] [JAVASCRIPT] [HTML] [CSS] Pessoa Desenvolvedora Python (Sênior) na [INVILLIA]

### ISSUE THREAD

**Issue by plgisele** [devssa/onde-codar-em-salvador#1578]
## Descrição da vaga

- Estamos buscando um profissional que antes de qualquer coisa ame programar e inovar e queira trabalhar de uma forma totalmente remota.
- Trabalhamos em um ambiente com total autonomia para novas soluções disruptivas e valorizamos isso, por isso estamos procurando alguém que compartilhe desse mindset.
- Devido a essa autonomia, precisamos estar sempre em sintonia, por isso uma boa comunicação é muito importante para nós.

**Responsabilidades e atribuições:**
- Desenvolver código através de definição de histórias; corrigir defeitos; executar testes; automatizar (unitários, TDD, integrados, funcionais);
- Experiência com arquitetura em Cloud (AWS); familiaridade com CI/CD, Git, Desenvolvimento Ágil, Docker. Análise estática de código-fonte (métricas)

## Local

- Home Office

## Benefícios

- Informações diretamente com o responsável pela vaga/recrutador.

## Requisitos

**Obrigatórios:**
- Frameworks web: Django,
- Messageria: Celery;
- Frontend: Javascript, HTML5, CSS3;
- Banco de dados relacionais e não relacionais
- Conceitos: DDD (Domain Driven Design), TDD (Test Driven Development) e Design Pattern; 
- Automação de testes (Unitários, Integrados e Funcionais Automatizados).

## Contratação

- a combinar

## Nossa empresa

- A Invillia é uma empresa global que vem revolucionando a maneira como game-changers expandem o poder de inovar, implementar tecnologias de ponta e desenvolver novas estratégias, produtos e serviços digitais.
- Nenhuma outra empresa no mundo atua como a Invillia.
- E o que torna nosso Global Growth Framework tão único e poderoso?
- Primeiro, dissolvemos os limites entre o físico e o virtual para ter em nosso time os melhores talentos do planeta.
- Criamos infinitas práticas e metodologias para que que cada squad seja super customizado e engajado na cultura e desafios de cada cliente.
- Adoramos usar ferramentas ágeis, métricas, inteligência de dados no dia-a-dia. Para que ideias e melhorias se multipliquem.
- Mas acreditamos que é na educação contínua, na abordagem mais humana e colaborativa que a mágica acontece.
- Novas oportunidades surgem. E a inovação nunca para. Infinite Digital Power.

## Como se candidatar

- [Clique aqui para se candidatar](https://invillia.gupy.io/jobs/624745?jobBoardSource=gupy_public_page)

**Comment by Ola-Ahmed-Harba** [comment]
I am interested in this job and ready to start, but I need to know the rest of the details

**Comment by BrendaCosta** [comment]
@Ola-Ahmed-Harba 

Hello, how is everything?
we only share vacancies, for more information please contact the company, through the post link
good luck!

**Comment by Ola-Ahmed-Harba** [comment]
Thank you, I did
Good Luck!..
