### ISSUE TITLE
Desenvolvedor(a) Android Júnior/Pleno na [CUBOS]

### ISSUE THREAD

**Issue by devssa** [devssa/onde-codar-em-salvador#158]
#### Nossa stack Android:

- Kotlin
- Testes usando JUnit, Mockito e Espresso
- MVP/CLEAN
- CI/CD
- Git

#### Responsabilidades e atribuições

- Participar ativamente nas etapas de ideação, planejamento e desenvolvimento dos produtos dos nossos clientes;
- Participar de discussão das tecnologias que serão utilizadas nos projetos;
- Desenvolvimento de aplicações nativas Android usando Kotlin, construindo layouts feitos por nossos designers, visando uma UX de excelência;
- Deploy com continuous integration / continuous deployment;
- Disposição para ajudar e compartilhar conhecimento;
- Ser curioso e estar disposto a se arriscar em novas tecnologias.

## Local

Salvador - Bahia

## Benefícios

- Vale refeição ou alimentação;
- Plano de saúde ;
- Plano odontológico;
- Vale transporte;
- Aulas semanais multidisciplinares.

#### Diferenciais

A Cubos existe para transformar a realidade ao seu redor. Temos um desejo pujante de criar, impactar, aprender e causar uma diferença significativa na vida das pessoas através da tecnologia.

Nosso alicerce é a educação: somos um hub, absorvendo, compartilhando, produzindo conhecimento. Todo esse conteúdo se reflete nos nossos serviços e produtos, culminando em entregas incríveis, com foco na melhor experiência para o usuário. Vamos além do desenvolvimento. Por isso, não nos limitamos pelo padrão, assumimos riscos que nos dão a adrenalina necessária para alcançar resultados desafiadores. Todos os dias cuidamos das pessoas: aquelas que estão na Cubos; aquelas que são familiares e amigos; aquelas que são parceiros; aquelas que vemos no dia a dia; aquelas que nos tocam.

Oferecemos um ambiente colaborativo com bastante café, flexibilidade, pessoas incríveis dispostas a aprender e ensinar. Usamos tecnologia porque dá acessibilidade de conhecimento, porque simplifica o mundo, porque tecnologia é sinônimo de evolução, porque tecnologia é consequência da própria existência humana. Criamos tecnologia com significado.

## Requisitos

**Obrigatórios:**
- Conhecimento em versionamento com Git;
- Sólido Conhecimento do SDK Android;
- Experiência com Kotlin;
- Experiência consumindo web services;
- SQLite/SQL;
- Experiência construindo layouts e estilos em Android.

**Diferenciais:**
- Familiaridade com padrões de projeto, MVP, CLEAN, MVVM;
- Experiência com testes unitários e instrumentados;
- RxKotlin / RxJava;
- Experiência com integração contínua;
- Apresentação de portfólio, Github ou similares;
- Língua inglesa.

## VEM PRA CUBOS! 

Somos uma desenvolvedora de softwares e, nos nossos projetos, utilizamos metodologias ágeis. Vamos muito além do desenvolvimento para fazer a diferença na vida das pessoas. Oferecemos um ambiente colaborativo, com uma galera massa trabalhando em busca da evolução contínua e prezando por fazer entregas foda.

﻿Buscamos pessoas fantásticas que se identifiquem com a nossa cultura e, principalmente, que queiram fazer e ser parte da nossa história.

O que acreditamos:

- Somos uma empresa focada no desenvolvimento das pessoas;
- Queremos ver os cúbicos crescendo e evoluindo sempre;
- Aprender e compartilhar é o nosso valor mais intenso;
- Nos importamos verdadeiramente com nossas entregas.

A Cubos é a equipe de desenvolvimento de algumas Startups: Zigpay, Zakpay, Meu Loc, Rurali.

## Como se candidatar

https://cubos.gupy.io/jobs/42765

**Comment by rafaassism** [comment]
Olá!

Poderiam fechar essa issue? Vamos abrir uma nova vaga com outro link para se candidatar.

Muito obrigada desde já :)
