### ISSUE TITLE
[REMOTO] [ESTÁGIO] Programa de Estágio - Tecnologia na [ALURA]

### ISSUE THREAD

**Issue by plgisele** [devssa/onde-codar-em-salvador#1734]
## Descrição da vaga

- O propósito do programa de estágio Scuba Team é encontrar pessoas dispostas a mergulhar em aprendizados com a gente nas áreas de Back-end | Front-end | Data Science | DevOps. Queremos proporcionar o desenvolvimento para, além de aprimorar seus conhecimentos, ajudar quem está em contato com a gente nas dúvidas dessas áreas. Gostamos de pessoas que tem prazer em ajudar e são curiosas, então, quando as encontramos, trazemos para perto. Mergulhe nessa com a gente!

**Atividades:**
- Participar do fórum da Alura Cursos Online para solucionar as dúvidas sobre o tema da sua área;
- Manter a comunicação com times de atendimento, comercial, conteúdo, marketing, desenvolvimento e - colaborar com as rotinas internas da área;
- Estudar muito e buscar sempre a melhoria contínua pessoal e do time.

## Local

- Home Office

## Benefícios

- Vale refeição: R$24,00/dia;
- Horários flexíveis;
- Desenvolvimento no que gosta de aprender;
- Projeto Universo - Um projeto interno para estagiárias, estagiários e jovens aprendizes desenvolverem suas habilidades e competências que ajudarão não só no meio profissional e não só na Alura, mas sim com aplicação onde quiser;
- Acesso gratuito e ilimitado a todas as plataformas de educação do Grupo Alura.
- Apoio home-office: R$80,00 por mês depositado junto com o salário;
- Convênio médico parcial de 70%,

## Requisitos

**Obrigatórios:**
- Estar cursando Ensino Superior em qualquer área de atuação;
- Goste de estudar e de mergulhar em tecnologia;
- Acredite no potencial transformador da educação;
- Ter afinidade com as áreas de tecnologia escolhidas.

## Contratação

- a combinar

## Nossa empresa

- No grupo Alura procuramos transformar o mundo e a vida das pessoas a partir da educação e da tecnologia. Para isso, procuramos unir nossas diferenças, aprender para crescer, construir em grupo fazendo o nosso melhor para, então, encantar nossas alunas e alunos. Mergulhe nessa com a gente!

## Como se candidatar

- [Clique aqui para se candidatar](https://trampos.co/oportunidades/710151-programa-de-estagio-scuba-team)

**Comment by brunohebling51** [comment]
Ola, boa tarde ! A vaga está disponível? No link ela nao aparece mais.. Obrigado!
