### ISSUE TITLE
[JAVA][REMOTO] Desenvolvedor(a) Back-end | Squad Ativação na Contabilizei

### ISSUE THREAD

**Issue by ContabilizeiVagas** [devssa/onde-codar-em-salvador#1745]
## Descrição da vaga

Com mais de 30 mil clientes, atuando em mais de 50 cidades do Brasil, a Contabilizei está mudando a maneira como o micro e pequeno empreendedor gerencia o seu negócio em nosso país por meio da tecnologia. Continuamos a crescer rapidamente, criando novos produtos e proporcionando que o empreendedor seja o contador de sua própria história.

O **Squad Ativação** é responsável por apoiar os clientes que estão iniciando sua jornada na Contabilizei. Esse time tem como missão propor e desenvolver as funcionalidades que facilitarão o processo tanto para os nossos clientes, quanto para a própria Contabilizei.

Acreditamos que a diversidade promove o crescimento sustentável. Na Contabilizei queremos que você seja a melhor versão de si, e as oportunidades são para todos. Valorizamos as diferenças, e estamos abertos a receber pessoas com quaisquer deficiências, gênero, etnia, orientação sexual e diferentes mindsets. Juntos, construímos a Contabilizei do nosso jeito.

**Essa oportunidade permite trabalho remoto, ou se preferir, poderá trabalhar em um modelo presencial/híbrido em nosso escritório em Curitiba (após a pandemia), além disso, todas as nossas vagas são regime CLT.**

## Local

- 100% Remoto (qualquer lugar do Brasil) ou Presencial/Híbrido em Curitiba após a pandemia.

## Benefícios

Nossos benefícios:
Vale Refeição e/ou Alimentação;
Plano de Saúde;
Plano Odontológico;
GymPass;
Convênio Farmácia;
Seguro de vida;
Psicoterapia Online;
Infraestrutura tecnológica de trabalho.

O que esperar da Contabilizei
Nossas Guardiãs e Guardiões acreditam e perseguem nosso propósito: Entendem que o sucesso do empresário é o nosso sucesso. Oferecemos um ambiente descontraído, completamente colaborativo, com ritmo acelerado e desafiador, a fim de atingir resultados e promover a melhor experiência aos nossos clientes, construindo uma jornada de sucesso. Acreditamos no protagonismo, aqui você constrói sua carreira da sua forma e cresce junto com a Contabilizei.

Aqui, você terá a oportunidade de gerar um grande impacto positivo, construindo o futuro de como os empresários brasileiros gerenciam seus negócios com sucesso.

## Requisitos

Você precisa de:

Graduação completa ou cursando em Análise de Sistemas, Engenharia da Computação ou áreas afins;
Experiência com desenvolvimento back-end em Java;
Experiência com banco de dados relacionais e não relacionais;
Experiência com sistemas distribuídos;
Experiência com Cloud;
Experiência com DevOps;
Experiência com abordagens de qualidade;
Experiência com metodologias ágeis.

## Contratação

- CLT

## Como se candidatar

-Candidatura simplificada pelo Linkedin: https://www.linkedin.com/jobs/view/2494307592

**Comment by jessicaalorena** [comment]
Atualizado.
