### ISSUE TITLE
[JAVASCRIPT] [VUE.JS] [REACT.JS] Desenvolvedor Front-End na Vollare

### ISSUE THREAD

**Issue by bresoares93** [devssa/onde-codar-em-salvador#1754]
<!-- 
==================================================
Requisitos obrigatórios
* Domínio de VueJS e/ou ReactJS
* Domínio de Javascript, HTML5 e CSS
* Experiência em trabalho com metodologia Ágil

Diferenciais
* Desenvolvimento de Telas usando como base Protótipos no AdobeXD
* Conhecimentos de Documentação de APIs com Postman, Swagger etc
* Comunicação e Trabalho em Equipe
* * Experiência com Metodologia ágil Scrum
* Experiência com React Native

MODELO DE TRABALHO HÍBRIDO
(Startup Feirense)

Enviar CVs e link do Github para: brenda.skyone@gmail.com

**Comment by BrendaCosta** [comment]
Bom dia @bresoares93 suas issues serão fechadas por não terem informações sobre a vaga
