### ISSUE TITLE
[JAVASCRIPT] [NODE.JS] [TYPESCRIPT] Desenvolvedor Full-Stack na Vollare

### ISSUE THREAD

**Issue by bresoares93** [devssa/onde-codar-em-salvador#1755]
<!-- 
==================================================

Requisitos obrigatórios

* Domínio de NodeJS
* Domínio de TypeScript
* Experiência em trabalho com metodologia Ágil
* Experiência com Bancos de dados não-relacionais
* Experiência com API Rest

Diferenciais
* Experiência com API GraphQL
* Experiência com Banco MongoDB
* Conhecimentos de Documentação de APIs com Postman, Swagger etc
* Comunicação e Trabalho em Equipe

MODELO DE TRABALHO HÍBRIDO
(Startup Feirense)

Enviar CVs e link do Github para: brenda.skyone@gmail.com

**Comment by BrendaCosta** [comment]
Bom dia @bresoares93  suas issues serão fechadas por não terem informações sobre a vaga
