### ISSUE TITLE
[PHP] [VUEJS] [LARAVEL] Desenvolvedor Fullstack na [OA]

### ISSUE THREAD

**Issue by gn794** [devssa/onde-codar-em-salvador#1926]
## Descrição da vaga

- A OA é uma startup baiana que busca uma pessoa desenvolvedora que seja organizada e tenha espírito de liderança. O desenvolvimento dos nossos projetos é majoritariamente em PHP, e necessitamos de melhorias agregadas ao software existente e manutenção ao sistema atual.

## Local

- Salvador 

## Requisitos

**Obrigatórios:**
- Experiência sólida com LARAVEL e PHP
- Proativa
- Organizada

**Diferenciais:**
- Estar antenada com as tendências das tecnologias do mercado.

## Contratação

- Imediata

## Como se candidatar

- Por favor envie um email para contato@orcaaqui.com.br com seu CV anexado - enviar no assunto: Vaga OA

**Comment by alexMaluco** [comment]
Vaga aberta?
