### ISSUE TITLE
[UX/UI] Designer na [CUBOS]

### ISSUE THREAD

**Issue by eduardocarvalho1** [devssa/onde-codar-em-salvador#213]
## Designer UX/UI na Cubos

A Cubos existe para transformar a realidade ao seu redor. Temos um desejo pujante de criar, impactar, aprender e causar uma diferença significativa na vida das pessoas através da tecnologia.

Nosso alicerce é a educação: somos um hub, absorvendo, compartilhando, produzindo conhecimento. Todo esse conteúdo se reflete nos nossos serviços e produtos, culminando em entregas incríveis, com foco na melhor experiência para o usuário. Vamos além do desenvolvimento. Por isso, não nos limitamos pelo padrão, assumimos riscos que nos dão a adrenalina necessária para alcançar resultados desafiadores. Todos os dias cuidamos das pessoas: aquelas que estão na Cubos; aquelas que são familiares e amigos; aquelas que são parceiros; aquelas que vemos no dia a dia; aquelas que nos tocam.

Oferecemos um ambiente colaborativo com bastante café, flexibilidade, pessoas incríveis dispostas a aprender e ensinar. Usamos tecnologia porque dá acessibilidade de conhecimento, porque simplifica o mundo, porque tecnologia é sinônimo de evolução, porque tecnologia é consequência da própria existência humana. Criamos tecnologia com significado.

## Local

Salvador

## Benefícios

- Vale refeição ou alimentação;
- Plano de saúde ;
- Plano odontológico;
- Vale transporte;
- Aulas semanais multidisciplinares.

## Requisitos

Requisitos:
- Forte conhecimento em boas práticas de experiência do usuário e usabilidade;
- Conhecimento de bibliotecas como Cupertino/Material Design;
- Boa noção de estética e design gráfico;
- Proficiente em ferramenta de UI — preferencialmente Sketch;
- Proficiência em Illustrator ou Photoshop;
- Conseguir calçar os sapatinhos do usuário e advogar a favor dele;
- Conseguir articular e defender decisões de design.

Diferenciais:
- Habilidades em motion design;
- Habilidades em ilustração;
- Conhecimento em ferramenta de prototipação de alta fidelidade.

Responsabilidades e atribuições:
- Realizar pesquisa e entrevista de usuário;
- Criar personas, user flows e user stories;
- Construir wireframes e protótipos interativos;
- Desenvolver interfaces de alta fidelidade para aplicativos, sistemas e websites;
- Realizar testes de usuário.

## Cubos

Somos uma desenvolvedora de softwares e, nos nossos projetos, utilizamos metodologias ágeis. Vamos muito além do desenvolvimento para fazer a diferença na vida das pessoas. Oferecemos um ambiente colaborativo, com uma galera massa trabalhando em busca da evolução contínua e prezando por fazer entregas foda.

﻿Buscamos pessoas fantásticas que se identifiquem com a nossa cultura e, principalmente, que queiram fazer e ser parte da nossa história.

O que acreditamos:

Somos uma empresa focada no desenvolvimento das pessoas;
Queremos ver os cúbicos crescendo e evoluindo sempre;
Aprender e compartilhar é o nosso valor mais intenso;
Nos importamos verdadeiramente com nossas entregas.

A Cubos é a equipe de desenvolvimento de algumas Startups: Zigpay, Zakpay, Meu Loc, Rurali.

## Como se candidatar

Inscreva-se a a partir do link: https://cubos.gupy.io/candidates/jobs/55984/apply

**Comment by rafaassism** [comment]
Olá!

Poderiam fechar essa issue? A vaga foi preenchida.

Muito obrigada desde já :)
