### ISSUE TITLE
Consultor de Implantação de ERP na [SIAGRA]

### ISSUE THREAD

**Issue by eduardocarvalho1** [devssa/onde-codar-em-salvador#244]
## Consultor de implantação de ERP

Vaga para consultor de implantação de ERP na SIAGRI

## Atividades

- Prestar consultoria presencial ou remota aos clientes. Efetuar levantamento e análise de requisitos para a implantação de ERP. Executar parametrizações do sistema, treinar usuários e realizar acompanhamento do início de operação, além de prestar suporte técnico até a conclusão da certificação do projeto. Realizar visitas de relacionamento e pós-venda e conduzir reuniões de negócios e negociar serviços.

·        Onboarding (implantação) de novos clientes:

Interpretar os processos do cliente a fim de identificar necessidades e sugestão de melhorias quando cabíveis. Parametrizar o sistema conforme a definição de processos e conduzir treinamentos aos usuários dos clientes.

  

·        Identificar casos de uso que possam ser escaláveis em outros clientes:

Contribuir com a aplicação das melhores práticas de gestão aplicadas no segmento de atuação do cliente, com o objetivo de apoiá-lo na evolução do seu negócio, garantindo que os benefícios da solução sejam perceptíveis.

 

·        Gerenciar a carteira de clientes:

Efetuar o planejamento e organização das operações de gerenciamento de pós-vendas.

Construir relacionamentos sustentáveis com os clientes, fazendo contatos e visitas periódicas aos clientes da base.

 

·        Conduzir reuniões e apresentações estratégicas e operacionais:

Engajar o cliente na utilização de nossas soluções e medir o resultado obtido. 

 

·        Dar feedbacks para os times internos (Comercial, Marketing e Serviços):

Compartilhar com os times internos as interações realizadas com os clientes.

## Local

-  Luis Eduardo Magalhães-BA / Barreiras-BA

## Benefícios

- Vale Alimentação ou refeição
- Plano de saúde e odontológico
- Lanche diário
- Estacionamento
- Bolsa de estudos
- Biblioteca
- Sala de jogos
- Sala de descanso/massagem
- Horário Flexível
- All casual day

## Requisitos

**Obrigatórios:**

- Curso Superior em Administração, Ciências Contábeis, Sistemas de Informação e Agronegócios ou áreas correlatas.

- Noções avançadas em Informática.

- Conhecimentos de processos administrativos, financeiros, compras, vendas, regras fiscais, contábeis, entre outros.

- Conhecimentos em processos do Agronegócio será um grande diferencial.

- Experiência em atendimento ao cliente.

- Experiência com implantação e parametrização de software.

- Experiência com realização de treinamentos.

- Experiência em gestão administrativa e ERP.

- Capacidade para negociação e argumentação.

- Habilidade para negociação em vendas e marketing de serviços.

**Diferenciais:**

## Contratação

- Salário: a combinar;
- CLT;

## SIAGRI

A SIAGRI nasceu no agro para atender as necessidades exclusivas do segmento, sendo hoje uma das empresas com mais visibilidade do país.

Nos destacamos no mercado nacional de tecnologia, oferecendo um portfólio completo para a gestão do agronegócio. Atualmente atendemos mais de 1.950 estabelecimentos, 40 mil usuários e gerenciamos mais de 1 milhão de hectares.

Nossas soluções são especializadas em otimizar processos e custos do agronegócio, abrangendo linhas de softwares de gestão empresarial, inteligência de negócios, aplicativos, entre outras. Porque afinal, nosso propósito é facilitar o trabalho de quem alimenta o mundo, é ajudar através da gestão e da tecnologia, nossos clientes a evoluírem em seus negócios e construírem histórias de sucesso.

Vem crescer junto com a gente. Vem ser SIAGRI!

## Como se candidatar

Link: https://siagri.gupy.io/candidates/jobs/60273/apply?jobBoardSource=linkedin

**Comment by devssa** [comment]
ISSUE FECHADA PELA DISTANCIA COM A REGIÃO METROPOLITANA DE SALVADOR, SOMENTE DIVULGAMOS VAGAS DE CIDADES COM ATÉ 70 KM DE DISTANCIA DO CENTRO DE SALVADOR
