### ISSUE TITLE
[Remoto] IT Audit na JJJ Air Software

### ISSUE THREAD

**Issue by ghost** [devssa/onde-codar-em-salvador#2468]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/auditoria-em-ti-de-servicos-e-ambientes-de-tecnologia-212507754?utm_source=github&utm_medium=devssa-onde-codar-em-salvador&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A JJJ Air Software</strong> busca pessoa <strong>IT Audit</strong> para compor seu time!</p>
<p>O projeto consistem em definir um checklist para aplicar uma auditoria no serviço prestado por um fornecedor de TI a uma empresa (cliente). Espera-se que a pessoa possa auditar e verificar a conformidade do fornecedor de TI para o cliente.&nbsp;</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Arquitetura</li>
<li>Banco de dados</li>
<li>&nbsp;Barramento</li>
<li>Tecnologias</li>
<li>Design pattenrs</li>
<li>Segurança</li>
<li>Performance</li>
<li>Escalabilidade</li>
</ul>
<p></p>

## JJJ Air Software: 
 <p>Empresa especializada em:</p>
<p>- Projetos de desenvolvimento de Software sob demanda</p><a href='https://coodesh.com/empresas/jjj-air-software'>Veja mais no site</a>

 ## Habilidades: 
 - Gestão de times de tecnologia 
- Technical Writers 
- .NET
## Local: 
 100% Remoto
## Requisitos: 
 - Conhecimento no processo de auditoria e compliance em TI 
- Experiência com a execução de checklist de conformidade em governança e compliance 
- Experiência em Due Diligence
## Diferenciais: 
 - Histórico e experiência com atividades de auditoria em TI, compliance e governança

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [IT Audit na JJJ Air Software](https://coodesh.com/vagas/auditoria-em-ti-de-servicos-e-ambientes-de-tecnologia-212507754?utm_source=github&utm_medium=devssa-onde-codar-em-salvador&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Gestão em TI

**Comment by luisaoba** [comment]
Bom dia , tudo bem?

Ja viram alguma vaga de BUBBLE?

Obrigado

Em ter., 24 de mai. de 2022 às 10:04, Gabriela Luz ***@***.***>
escreveu:
