### ISSUE TITLE
[Recife, Pernambuco, Brazil] Functional Consultant na Coodesh

### ISSUE THREAD

**Issue by blankapf** [devssa/onde-codar-em-salvador#3360]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/consultor-funcional-160110332?utm_source=github&utm_medium=devssa-onde-codar-em-salvador&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A <strong>Samba</strong> está em busca de <strong><ins>Functional Consultant</ins></strong> para compor seu time!</p>
<p>Para essa oportunidade buscamos uma pessoa para atuar em regime <strong>PJ e presencial em Recife (PE)</strong>. Procuramos alguém com propósito forte e que esteja disposta a trabalhar em ambiente colaborativo e dinâmico, pronto para crescer profissionalmente junto com a nossa equipe fora da curva! A Samba gosta de fazer a diferença sempre e nosso time é o responsável para que isto aconteça! Por isso, a gente espera que você seja uma pessoa apaixonada por tecnologia, assim com a gente! Todas as nossas vagas também se aplicam a pessoas com deficiência, então fique à vontade para se candidatar!</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Prestar consultoria em sistemas (melhorias, inovações, parametrizações, manutenções e atualizações) junto aos clientes internos em demandas de menor complexidade;</li>
<li>Analisar demandas das áreas de negócio e escrever a especificação funcional p/ desenvolvimento de sistemas;</li>
<li>Acompanhar o cronograma de execução e entrega da solução;</li>
<li>Homologar a solução desenvolvida junto ao cliente;</li>
<li>Elaborar a documentação da solução desenvolvida;</li>
<li>Implementar as demandas de sistemas de menor complexidade;</li>
<li>Parametrizar sistemas, de acordo com as regras de negócio;</li>
<li>Treinar e Capacitar usuários finais.</li>
<li>Realizar a gestão de projetos de sistemas, envolvendo: definição de escopo, planejamento, gestão da comunicação, monitoramento e controle, recursos e contratos;</li>
<li>Solicitação e avaliação de orçamentos.</li>
</ul>
<p>Legal, não é mesmo? Se candidate a esta vaga ou divulgue para alguém que você acredita que pode fazer parte do nosso time!</p>

## Samba Tech: 
 <p>A Sambatech é uma das empresas mais inovadoras do mundo, segundo a Fast Company, e é referência no mercado de vídeos online. Nossa empresa garante infraestrutura de alta qualidade para venda, distribuição, gerenciamento e armazenamento de vídeos e ajuda pessoas e empresas a terem mais sucesso, independentemente do seu objetivo.</p>
<p>Com suas soluções, a Samba atende diferentes tipos de necessidades relacionadas aos conteúdos audiovisuais e possui uma equipe totalmente focada em assegurar que nossos clientes tenham acesso ao que há de melhor em tecnologia para vídeos online.&nbsp;&nbsp;&nbsp;</p><a href='https://coodesh.com/empresas/samba-tech'>Veja mais no site</a>

 ## Habilidades: 
 - Análise de requisitos 
- Gestão de times de tecnologia 
- Ciclo de vida de desenvolvimento de sistemas
## Local: 
 Recife, Pernambuco, Brazil
## Requisitos: 
 - Ferramentas de gestão de projetos - Intermediário; 
- Sistemas: AX / REMEDY / HCM / WEB / MASTERSAF / POLIBRAS - Intermediário; 
- Mapeamento de processos - Intermediário; 
- Levantamento de requisitos - Intermediário; 
- Técnicas de apresentação - Intermediário; 
- Método de análise e solução de problemas - Intermediário; 
- Inglês – Básico; 
- Espanhol - Básico.

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Functional Consultant na Samba Tech](https://coodesh.com/vagas/consultor-funcional-160110332?utm_source=github&utm_medium=devssa-onde-codar-em-salvador&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
PJ
#### Categoria
Gestão em TI

**Comment by luisaoba** [comment]
Já fiz o unsubscribed da lista mas continuo a receber. podem me tirar da lista? Obrigado

**Comment by me42th** [comment]
@luisaoba vc precisa desfazer o "watch", essa é uma funcionalidade do github...

![image](https://user-images.githubusercontent.com/26856017/202726035-5d22b0cf-8e3f-4cc9-9dd8-c6c34377ec04.png)
