### ISSUE TITLE
Desenvolvedor Web na [INFOCRAFT]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#365]
## Local

- Salvador 

## Benefícios

- Seg. a sexta, 08h às 17h com 1h de almoço

## Requisitos

**Obrigatórios:**
- Laravel
- Conhecimento em arquitetura REST

**Desejáveis:**
- AngularJs

**Diferenciais:**
- Ionic
- VueJs
- Angular

## Contratação

-CLT

## INFOCRAFT

- Empresa de TIC que fornece produtos e serviços  nos segmentos público e privado.
## Como se candidatar

- Enviar curriculo e pretensão salarial para infocraft@infocraft.com.br

**Comment by davidweezing** [comment]
Oi Brenda, já desenvolvi sistemas em PHP roots... Não trabalhei muito com Laravel... Sou muito bem resolvido JavaScripamente! Dá pra candidatar? ^^
