### ISSUE TITLE
[Hibrido / Itu/SP] UX/UI Designer na Coodesh

### ISSUE THREAD

**Issue by blankapf** [devssa/onde-codar-em-salvador#3651]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/ux-analista-de-negocios-e-experiencia-122557446?utm_source=github&utm_medium=devssa-onde-codar-em-salvador&modal=open) com o pop-up personalizado de candidatura. 👋
<p>A Auto Geral está em busca de UX/UI Designer para compor seu time!</p>
<p>A Auto Geral é uma empresa de autopeças atuante desde 1967, nós utilizamos a tecnologia para tornar a vida dos colaboradores e clientes mais fácil e reduzir atritos.</p>
<p>Responsabilidades:</p>
<ul>
<li>Realizar pesquisas com os nossos clientes e colaboradores para definir mudanças nos sistemas e suas interfaces;</li>
<li>Definir como deverão ser estas interfaces e o fluxo entre as telas e cada ação que irá ocorrer.</li>
</ul>
<p>Esta função responderá para a área de qualidade e terá interfaces com a gestão, vendas, logística e desenvolvimento.</p>
<p></p>

## Auto Geral Autopeças: 
 <p>O progresso da Auto Geral não aconteceu por acaso, tampouco foi um golpe de sorte. Mas o crescimento deve-se exclusivamente ao esforço de uma equipe que esteve 100% envolvida e comprometida com a empresa durante todos esses anos, desde 1967. Em 2015 iniciou sua caminhada rumo a certificação ISO 9001, estando hoje na sua recertificação. São mais de 50 anos de história, de progresso e hoje a Auto Geral é uma empresa regionalmente reconhecida no setor de auto peças com lojas em Itu, Sorocaba, Salto, Porto Feliz, Indaiatuba, Cabreúva, Tatuí, Boituva, Piedade e Cerquilho. Ao todo contamos com mais de 200 funcionários. E no que estamos pensando agora? Nos próximos 50 anos.</p>
</p>

 ## Habilidades: 
 -  UX/UI 
- Adobe XD 
- HTML
## Local: 
 Itu/SP
## Requisitos: 
 - Boa comunicação escrita e oral; 
- Elaboração de diagramas e especificações de telas.
## Diferenciais: 
 - Gestão enxuta; 
- SQL.
## Benefícios: 
 - VR; 
- Unimed.
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [UX/UI Designer na Auto Geral Autopeças](https://coodesh.com/jobs/ux-analista-de-negocios-e-experiencia-122557446?utm_source=github&utm_medium=devssa-onde-codar-em-salvador&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Alocado
#### Regime
CLT
#### Categoria
Design/UX

**Comment by gabe-oliveira** [comment]
Candidatura enviada :)
