### ISSUE TITLE
Desenvolvedor Web Jr na [SOTERO TECH]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#386]
## Local

- LAURO DE FREITAS

## Benefícios

- Carga horária de 44h/semanais
- Ambiente de trabalho descontraído
- Salário + VT + VA

## Requisitos

**Obrigatórios:**
- Ensino superior completo
- Angular 6+
- Javascript ES6+
- Consumo de API'S Rest
- HTML + CSS

**Diferenciais:**
- .NET - C#
- GIT
- SCRUM
- CONSTRUÇÃO DE TESTES AUTOMATIZADOS

## Nossa empresa

Somos uma empresa brasileira de tecnologia digital e estamos localizados na região metropolitana de Salvador, na Bahia.

Realizamos trabalhos de destaque em pesquisa, concepção, coordenação e desenvolvimento de projetos nas áreas de Marketing, Comunicação, Tecnologia e Arte Digital, combinando inovação e praticidade na criação dos nossos projetos. Focada no atendimento das necessidades dos clientes, a Sotero Tech busca o que há de melhor em tecnologia no mercado mundial, visando agregar valor aos serviços e produtos, além de atrair e conquistar o público consumidor.

Desenvolvemos soluções atráves de Sistemas Web, Aplicativos Móveis, Jogos, Realidade Aumentada, Simuladores, dentre outros.## Como se candidatar

Por favor envie um email para email@email.com.br com seu CV anexado - enviar no assunto: Vaga NodeJS

## Como se candidatar

Envie seu CV, pretensão salarial e portfólio/github com o assunto [Vaga Angular] para selecao@soterotech.com.br

**Comment by raloliver** [comment]
Ainda aberta?

**Comment by me42th** [comment]
@raloliver a gnt apenas mapeia as vagas, imagino que sim pois tem pouco tempo e as vagas demoram algumas semanas pra serem preenchidas...

já tentou entrar em contato com eles?

**Comment by raloliver** [comment]
Sim, já fechou. Recebi a resposta por email.

**Comment by BrendaCosta** [comment]
Obrigada @raloliver  vamos fechar aqui também!
