### ISSUE TITLE
[ESTÁGIO]  PROGRAMADOR WEB na [ZWA]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#387]
## Local

 - Lauro de Freitas

## Benefícios

- Bolsa auxilio
- Vale transporte

## Requisitos

**Obrigatórios:**
- Cursando ensino superior em cursos na área de TI
- Conhecimento em programação web ( HTML, PHP, CSS, Javascript)
- Conhecimento em desenvolvimento Wordpress
- Disponibilidade para o turno vespertino

## Contratação

- Estágio
 
## ZWA

- Oferecemos soluções em comunicação visual, impactando mensagens com diferencial exclusivo em design.

## Como se candidatar

- curriculo para curriculo@zwa.com.br

**Comment by Brn677** [comment]
Currículo enviado. ;)
