### ISSUE TITLE
DESENVOLVEDOR DOTNET na [RECONCAVO]

### ISSUE THREAD

**Issue by me42th** [devssa/onde-codar-em-salvador#413]
:sunglasses: :sunglasses: :sunglasses:  <kbd>⇥ SALVADOR ↩</kbd> :sunglasses: :sunglasses: :sunglasses:
## DESENVOLVEDOR DOTNET
:sunglasses: :sunglasses: :sunglasses: <kbd>⇥ SALVADOR ↩</kbd> :sunglasses: :sunglasses: :sunglasses:

## Requisitos
- .NET
- C#
- .NETCORE
- MODELAGEM DE SISTEMAS
- TRANSAC-SQL E ANGULAR
- JQUERY
- JAVASCRIPT
- CSS
- DOCUMENTAÇÃO DE SISTEMAS

## Como se candidatar :exclamation:

ENVIAR CURRICULO PARA **rh@reconcavo.org.br**

**Comment by raloliver** [comment]
Ainda aberta?

**Comment by me42th** [comment]
@raloliver a gnt apenas mapeia as vagas, imagino que sim pois tem pouco tempo e as vagas demoram algumas semanas pra serem preenchidas...

já tentou entrar em contato com eles?

**Comment by raloliver** [comment]
Sim, mas não responderam ainda.
