### ISSUE TITLE
Analista de Redes na [SOLUTIS]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#423]
## Analista de Redes

Para essa oportunidade buscamos um profissional dinâmico, em buscas de novas desafios para atuar como Administrador de Redes.

## ATIVIDADES
- Realizar serviços nos equipamentos da rede local, como instalação e configuração de computadores e ativos de rede;
- Prestar suporte a área de desenvolvimento de aplicações, registrar ocorrências, orientar usuários, acompanhar e eliminar falhas;
- Negociar a contratação de serviços e produtos, acompanhando contratos de manutenção de programas;
- Fornecer suporte a área de redes do cliente e atuando com processos;
- Monitorar os serviços e equipamentos da rede para garantir que estejam funcionando dentro do padrão esperado;
- Executar configurações em CMTS, Roteadores, Switches e Servidores;
- Realizar suporte a técnicos de campo e outros setores internos com o intuito de solucionar problemas relacionados aos serviços prestados.

## Local

- Salvador 

## Requisitos

**Obrigatórios:**
- Redes TCP/ IP, protocolos Ethernet e em protocolos de roteamento: AS, OSPF e BGP-4;
- Conhecimento em firewalls (Fortinet e Iptables - Linux);
- Conhecimento em serviços de rede (DHCP, TFTP, DNS e LDAP);
- Configuração de ferramentas de monitoramento de rede, utilizando (cliente, portas e protocolos, SMNP e ICMP), em especial, Zabbix;
- Experiência com Trunks, LAG, Spanning-tree, Vlans, Routing Protocols.

**Desejáveis:**
- Conhecimento em sistemas operacionais Solaris e Linux;
- Conhecimento em IPv6;
- Certificação CISCO.

## SOLUTIS

Somos apaixonados por gente e esse valor está presente em nossas ações e proposta de trabalho. Ambiente descontraído e criativo, horário flexível, possibilidade de trabalho home office, eventos e programas internos com games... Isso faz parte do nosso dia-a-dia.

Engajamento, busca intensa por conhecimento, empatia e criatividade são a nossa receita para cultivar e colher, sempre, o melhor resultado tecnológico.

Essa é a Solutis, flexível, acolhedora, inquieta, amante da tecnologia e de tudo que ela nos proporciona de mais incrível.

Venha fazer parte do nosso time!

## Como se candidatar

LINK: https://solutis.gupy.io/jobs/77509

**Comment by leoglima85** [comment]
Bom dia brenda, tem alguma vaga para Jr ? tenho expereciencia em alguns dos requisitos (TCP-IP,DHCP, TFTP, DNS e LDAP, SNMP, Zabix, the Dude, Whats Up Gold, um pouco de linux fui usuario do slackware por uns 2 anos, um pouco de conhecimento em Roteadores, Switches, servidores windows ). valewww

**Comment by BrendaCosta** [comment]
Oi @leoglima85, bom dia!
Não vi nenhuma vaga ultimamente com essas especificações, mas se souber de alguma coisa posto aqui no repositório!
Boa sorte
