### ISSUE TITLE
Analista de Sistemas JR (Java) na [CAPGEMINI]

### ISSUE THREAD

**Issue by me42th** [devssa/onde-codar-em-salvador#427]
# VAGA: Analista de Sistemas JR (Java)

## Requisitos:
- Curso superior completo de graduação na área de Tecnologia da Informação.
- Java e orientação a objeto.         
- Framework Spring Boot
- **Frontend:** HTML 5, CSS3, Angular 5, Javascript, TypeScript, Jquery, Bootstrap;
- **Testes:** JUnit, Selenium, TDD;
- **Servidores de aplicação:** JBoss/Wildfly;
- Experiência em integração de sistemas através de Web services (SOAP/REST).
- Json, XML, NodeJS;
- Mensageria;
- JAAS e oAuth2;
- **Bancos de Dados:** Oracle SQL, PL/SQL, Postgre/Postgis para os dados espaciais, JPA: Hibernate; Git.

# Interessados, encaminhar o currículo para: maria-carolina.ferreira@capgemini.com

**Comment by guilhermeoa07** [comment]
Qual a média salarial?

**Comment by me42th** [comment]
> Qual a média salarial?

A gnt só posta a vaga, já tentou contato com o email?
