### ISSUE TITLE
[PLENO] Desenvolvedor Back-end PHP na [SANAR]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#527]
## Local

- Salvador 

## Benefícios

- Vale Transporte ou Auxílio Gasolina
- Vale Alimentação ou Refeição
-  Plano de Saúde

#### Diferenciais

- Não temos Dress Code. Você pode vir vestido como quiser (respeitando sempre o outro).
- Aula de Inglês na própria Sanar. Independente do quanto você já sabe, aqui você tem a possibilidade de ter aulas toda semana com nosso teacher, pra aprimorar, aprender, praticar...
- Happy Hour Semanal. Toda semana temos um momento de descontração para nossos sanáticos.
- Sala de Descanso feita  pra quem precisa relaxar e descansar um pouco ou pra aquela sonequinha depois do almoço.
- Equipamentos necessários para realizar o seu trabalho. Aqui você não precisa trazer os seus materiais. A Sanar ficará encarregada de entregar tudo que você precisa.
- Instrumentos Musicais para você mostrar seu talento pra gente.
- Jogos para você relaxar. Temos aqui ping pong e xbox.

## Requisitos

**Obrigatórios:**
- PHP Orientado a Objeto;
- Frameworks PHP (Laravael, CodeIgniter...);
- API REST;
- Docker;
- TDD;
- Bancos de dados Relacionais (MySQL / PostgreSQL).

**Diferenciais:**
- Micro-serviços
- Bancos de Dados Não Relacionais (MongoDB)
- Modelagem de Banco

## Contratação

- a combinar

## Sanar
- Sanar em uma empresa digital e de uso criativo das mais modernas  tecnologias. Queremos inovar e criar uma experiência relevante para os nossos clientes e para a comunidade de Saúde através de plataformas de educação e de acesso a diversos tipos de conteúdo.

## Como se candidatar

- LINK: https://jobs.kenoby.com/sanar/job/desenvolvedora-back-end-php-pleno/5db332069a7dc95238478a13

**Comment by ricking007** [comment]
Quero muito essa vaga
