### ISSUE TITLE
Estágio em Tecnologia da Informação na [SECIS]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#528]
## Descrição da vaga

Estágio em Tecnologia da Informação

## Local

Sede da SECIS, Rua da Grécia, Bairro: Comércio.

## Benefícios

- Meio Turno: Manhã ou Tarde
- Bolsa: R$ 618,18
- Transporte: R$ 132,00

## Requisitos

**Obrigatórios:**
- O candidato deve estar cursando o 6º semestre , ou superior, dos cursos de Bacharelado/Engenharia em TI/Computação ou afins; ou o 4º semestre, ou superior, dos cursos Tecnológicos em TI/Redes e afins.

**Atividades:**
- Suporte técnico ao usuário de micro-computador: MS Office, Internet e serviços de impressão;
- Manutenção de microcomputador;
- Suporte a rede de computadores e telefonia: Instalação e manutenção de pontos de voz e dados. Monitoramento proativo dos recursos de rede (equipamentos e serviços) através de software.

## Contratação

- Estágio

## SECIS

A Secretaria Municipal de Sustentabilidade, Inovação e Resiliência

## Como se candidatar

- LINK:  https://docs.google.com/forms/d/e/1FAIpQLSfh-dS1tT2gaLZXANKBkj3XFo0YWJGzAJi6607jxUvayvzP_w/viewform

**Comment by wesleysilva2** [comment]
A vaga é interessante, mais parece que o formulário não está disponível 😥, pede algum tipo de acesso especial.

**Comment by BrendaCosta** [comment]
@wesleysilva2  Deve ter sido fechada já :( 
Vou fechar aqui tbm...

**Comment by wesleysilva2** [comment]
Entendi 😅, bom sempre alerta para as vagas rsrs.

Obrigado pela atenção.

Em dom., 1 de dez. de 2019 às 19:00, BrendaCosta <notifications@github.com>
escreveu:
