### ISSUE TITLE
[REMOTO] Desenvolvedor(a) Frontend Junior na [Instruct]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#555]
## Descrição da vaga

- Estamos buscando uma pessoa que consiga trabalhar em um time multidisciplinar, que tenha bons conhecimentos em desenvolvimento web, criando interfaces, implementando frontend e integrando com backend.
- Você fará parte de uma equipe que desenvolve soluções de automação de alto impacto na operação de TI de nossos clientes.
- Sua maior responsabilidade será desenvolver interfaces desde o desenho, passando pela implementação do HTML, CSS e JavaScript e integrações com backend.
- É fundamental saber aprender novas tecnologias e que você goste de compartilhar o seu conhecimento com outras pessoas. Ser curioso e autodidata são características bem-vindas e importantes.
- O trabalho poderá ser realizado totalmente remoto, dentro de horário comercial e seguindo o horário de Brasília, com ocasionais viagens a São Paulo, Brasília, Campinas e Rio de Janeiro para encontros com a equipe ou clientes, custeados pela empresa. Portanto, é fundamental ter disponibilidade para viajar.
- Nós não perguntamos pretensão salarial. Se identificarmos que você é a pessoa que queremos ter em nossa equipe, faremos uma proposta financeira condizente dentro da faixa salarial inicial da empresa.

## Local

- Remoto 

## Benefícios

- Regime de contratação CLT;
- Salário inicial entre R$ 2.00,00 e R$ 3.000,00;
- Plano de saúde e odontológico Bradesco Top Nacional Top para o titular e seus dependentes;
- Vale refeição de R$ 400,00;
- Vale alimentação de R$ 600,00;
- Seguro de vida corporativo custeado pela empresa;
- Verbas para investimento em treinamentos e educação;
- Acesso aos treinamentos da empresa sem custos;
- Prêmio de participação nos resultados;
- Prêmio quando se completa aniversário de empresa;
- Laptop Dell Inspiron 14 5480 (Core i7-8565U, RAM 16GB, GeForce MX150, HDD 1TB, SSD 128GB, Full HD);

#### Diferenciais

- Ambiente de trabalho amigável, inclusivo e seguro;
- Resolvemos problemas desafiadores e em larga escala para nossos clientes;
- Incentivos para participação em eventos, cursos e palestras;
- Usamos ferramentas e métodos inteligentes e inovadores para interagir com nosso time;
- Cultura blameless;
- Café de qualidade!

## Requisitos

**Obrigatórios:**
- HTML 5 e noções de acessibilidade;
- CSS 3 e Flexbox;
- Javascript (ES6+);
- Noções básicas de UI/UX;
- Integração de aplicações via APIs REST;
- Uso de Git para versionamento de seu código;

**Desejáveis:**
- Desenvolvimento de algum projeto Frontend sem a utilização de libraries ou frameworks;
- Uso de aplicações visuais como Figma, Sketch ou Illustrator;
- Automatizadores e Bundlers: Gulp, Webpack, etc;
- SCSS e BEM;
- Experiência com Vue.js;
- Ferramentas de testes JavaScript: Jasmine, Jest ou Mocha;

**Diferenciais:**
- Fundamentos de modelos ágeis como Kanban e Scrum;
- Fundamentos do conceito testes unitários;
- Analise e desenho de interfaces utilizando Figma;
- SCSS e BEM;
- Vue.js e Node.js;
- GitLab CI;
- Participação em projetos Open Source;

## Contratação

- CLT

## Nossa empresa

- Somos uma empresa de desenvolvimento de software e consultoria especializada em tecnologias e metodologias voltadas para criação de processos eficientes e automatizados, redução de riscos e aceleração na entrega de software e recursos de TI.

## Como se candidatar

[SE INSCREVA AQUI](https://hipsters.jobs/job/4512/desenvolvedor-a-frontend-junior-remoto/)

**Comment by tiago-sn** [comment]
A vaga está fechada?

**Comment by BrendaCosta** [comment]
Olá @tiago-sn somos apenas responsáveis por compartilhar as vagas, para maiores detalhes entre em  contato com eles... mas ao clicar no link para se candidatar vejo que a vaga já foi preenchida
