### ISSUE TITLE
Estágio em Desenvolvimento de Software na [TECNO TRENDS]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#626]
## Descrição
- Nós daremos todo o treinamento necessário!
- O nosso objetivo é captar alunos de Instituições de Ensino Superior com interesse em ter uma experiência profissional no mercado de trabalho que seja complementar ao ensino na universidade. Não é necessário que o aluno tenha conhecimento em alguma tecnologia específica para participar do programa. Oferecemos um período de treinamento, em que os alunos ingressantes serão capacitados nas tecnologias e ferramentas que serão utilizadas durante o estágio. No entanto, é necessário que o aluno possua conhecimento em lógica de programação e tenha um bom raciocínio lógico, além de muita vontade e disposição para aprender novas tecnologias.

## Local

- Salvador 

## Requisitos

**Obrigatórios:**
- Desenvolver novas funções para os software, utilizando C#, ASP.NET e SQL SERVER

## Contratação

- Estágio

## Nossa empresa

- A TecnoTRENDS, fundada em 1993, consegue aliar a sua rica experiência no mercado de ensino à capacidade técnica para desenvolver modernos aplicativos de gestão acadêmica.

## Como se candidatar
- Valido até dia 11/02/2020
- [Clique aqui para se candidatar](http://bit.ly/estagio_Tecnotrends_20201)

**Comment by willnettolobo** [comment]
Boa noite, o link não está funcionando.

**Comment by devssa** [comment]
@willnettolobo tenta agora
