### ISSUE TITLE
[REMOTO] Analista de Testes na [Essence ]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#639]
## Local

- REMOTO

## Requisitos

**Obrigatórios:**
- Experiência com testes Mobile e Web;
- Conhecimentos em Ruby

## Contratação

- a combinar

## Nossa empresa

- Especializada em soluções de tecnologia da informação desde 2004, a Essence possui um DNA voltado a performance e grandes resultados. Com um time formado por pessoas altamente capacitadas e de habilidades complementares, nossa linha de atuação está focada em serviços desenhados sob medida em quatro unidades de negócio:

## Como se candidatar

- Interessados enviar CV e valor pretendido para: maryana.silva@essenceit.com

**Comment by Daniray2008** [comment]
Ola gostaria de saber se ainda estao contratando, se tem alguma oportunidade para analista de teste para estagio ou jr?
