### ISSUE TITLE
Desenvolvedor Web na [LEVEL 131]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#648]
## Local

- Salvador 

## Requisitos

**Obrigatórios:**
- Buscamos desenvolvedores com conhecimentos sólidos em HTML5, CSS3, PHP, JavaScript e Bootstrap.

## Contratação

- a combinar

## Nossa empresa

- Somos uma agência digital especializada na criação e desenvolvimento de soluções web e mobile.
Nosso objetivo é unir o nosso know-how ao das agências de publicidade para produzir as melhores experiências e conectar marcas a pessoas, por meio de soluções interativas e inovadoras.

## Como se candidatar

- [Interessados devem preencher o curto formulário](https://forms.gle/8Nns8LKdWzEqdXYw5)
- Caso tenham algum problema na utilização do formulário enviar currículo para vagas@level131.com | Assunto: Vaga Desenvolvedor Web

**Comment by Mr-Fullstack** [comment]
olá, estou a para lançar uma agência web brevemente, mais gostaria de uma oportunidade de contribuir com meu trabalho, preciso ter mais experiências de gerência de projetos, será bastante útil ter uma renda fixa para poder fazer meu négocio crescer, mais quero que empresa não seja apenas o patrão, procuro uma empresa que seja parceira, que proporcione troca de experiências e seja mais transparente

**Comment by devssa** [comment]
@Mr-Fullstack top a iniciativa de empreender, entra no grupo do telegram e talvez alguem cole contigo...

Nós apenas cadastramos o conteudo, não somos responsaveis por ele...

**Comment by Mr-Fullstack** [comment]
opa, vlw vou tentar pelo email também, obrigado por lembrar!
