### ISSUE TITLE
[ESTÁGIO]  Desenvolvedor Web na [E-RURAL]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#659]
## Local

- Salvador 

## Requisitos

**Obrigatórios:**
- Conhecimento em desenvolvimento web (back-end e/ou front-end);
- Experiência com algum framework MVC;

**Desejáveis:**
- conhecimentos em ruby on rails

## Contratação

- Estágio

## Nossa empresa

- A e-rural é uma startup baiana que busca impactar o comércio de animais da pecuária, utilizando tecnologia para prover mais eficiência, segurança e resultados. Atualmente, atuamos com alguns modelos de negócios em distintas fases de maturação (expansão, validação e projeto), todos sempre com o mesmo propósito inicial. Conheça um pouco mais em: www.erural.net

## Como se candidatar

- E-mail com currículo/GitHub ou dúvidas para erbetta@erural. net

**Comment by wesleysilva2** [comment]
Ficou com duvida em como se candidatar, eu devo mandar meu currículo para erbetta@erural. net ou este contato é apenas para duvidas  ?

**Comment by BrendaCosta** [comment]
Oi @wesleysilva2 é pra vc mandar seu curriculo e github para o e-mail disponibilizado. 
Quando ele diz: " ..ou dúvidas", ele quer dizer, caso tenha alguma dúvida sobre a vaga pode entrar em contato. Boa sorte!

**Comment by wesleysilva2** [comment]
Há sim então fiz corretamente o processo, obrigado Brenda.
