### ISSUE TITLE
ANALISTA DE SISTEMA na [ATAKAREJO]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#672]
## Descrição da vaga

- Atender o segundo nível de atendimento a chamado de sistemas, soluções, sugestões, etc
- Elaborar atendimento remoto e presencial
- Diagnosticar falhas nos sistemas RMS, RM, SOCIN, BLCM, ENGEMAN e outros
- Orientar os usuários sobre procedimentos operacionais padrões e melhores práticas para uso dos sistemas 
- Monitorar os chamados aos fornecedores
- Controlar os acessos aos sistemas 
- Garantir o cumprimento dos requisitos dos clientes (SLA) acordado pela empresa
- Acompanhamento de chamados junto a fornecedores
- Elaborar apresentações executivas sobre os projetos 
- Realizar testes unitários e integrados em sistema 
- Dentre outras atividades 

## Local

- Salvador 

## Requisitos

**Obrigatórios:**
- Superior completo na área de Tecnologia  
- Experiência anterior na função 
- Experiência no segmento de varejo
- Conhecimento em UML, Banco de Dados, Mapeamento de Processos 

**Desejáveis:**
- Desejável pós-graduação em Engenharia de softwares/ Desenvolvimento de software

**Diferenciais:**
- Experiência com RMS e E-Connect (SOCIN)

## Contratação

- a combinar

## Nossa empresa

- O Grupo Atakarejo é uma empresa brasileira do ramo de supermercados com sede em Salvador, Bahia. 

## Como se candidatar

- [Clique aqui para se candidatar](https://jobs.kenoby.com/atakarejo/job/analista-de-sistema/5e4c018bbb61864768315631)

**Comment by alexMaluco** [comment]
Me desculpem pela minha intromissão, mas acredito que a vaga se enquadraria mais como Analista de Suporte.

**Comment by devssa** [comment]
@alexMaluco precisa pedir desculpa não, fica sussa...
Apenas centralizamos informação que encontramos na internet, não temos nenhuma relação com a empresa que divulgou a vaga...
