### ISSUE TITLE
Pessoa Desenvolvedora Backend Júnior na [CUBOS]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#690]
## Descrição da vaga

- Como dev backend você trabalhará desenvolvendo soluções tecnológicas que geram um impacto e que trazem significado para a vida das pessoas.

## Local

- Salvador 

## Benefícios

Não descontamos benefícios do salário.

- Vale refeição ou alimentação (R$ 26,00 por dia);
- Plano de saúde;
- Plano odontológico;
- Vale transporte (também pago em um cartão de crédito);
- Happy hour mensal;﻿
- Aulas semanais multidisciplinares.

## Requisitos

**Obrigatórios:**
- Experiência com Javascript;
- Conhecimento de web server (REST, RPC, graphQL);
- Saber debbugar o código;
- Dominar alguma linguagem;
- Conhecimento básico de Bash;

**Desejáveis:**
- Domínio de Javascript (NodeJs);
- Conhecimento de tipos de teste;
- Conhecimento de Design Patterns;
- Noção de CI/CD;
- Saber documentar;
- Saber tratar erros e falhas.

## Contratação

- a combinar

## Nossa empresa

- A Cubos existe para transformar a realidade ao seu redor. Temos um desejo pujante de criar, impactar, aprender e causar uma diferença significativa na vida das pessoas através da tecnologia. 

## Como se candidatar

- [Clique aqui para se candidatar](https://cubos.gupy.io/jobs/168741?jobBoardSource=gupy_public_page)

**Comment by mgalvc** [comment]
Possibilidade de remoto?

**Comment by BrendaCosta** [comment]
Olá @mgalvc nós apenas compartilhamos as informações que são públicas, você pode clicar no link para mais informações ou entrar em contato com a empresa
