### ISSUE TITLE
Desenvolvedor(a) Mobile React Native Júnior na [SANAR]

### ISSUE THREAD

**Issue by BrendaCosta** [devssa/onde-codar-em-salvador#695]
## Descrição da vaga

- Hoje, nossa equipe de Tecnologia & Engenharia da SANAR é dividida nas macroáreas de Growth, Plataform, Foundation, Hub e Mobile. Na unidade de negócio de Medicina, temos grandes desafios para a área, sendo estes: o grande escalonamento do time nos últimos meses, bem como o aumento da sua senioridade. Na área técnica, os desafios estão relacionados a escalonamento dos produtos e ao desenvolvimento de novos.

## Local

- Salvador 

## Benefícios

- Vale Transporte ou Auxílio Gasolina
- Vale Alimentação ou Refeição
- Plano de Saúde 
- Não temos Dress Code. Você pode vir vestido como quiser (respeitando sempre o outro).
-  Aula de Inglês na própria sanar. Independente do quanto você já sabe, aqui você tem a possibilidade de ter aulas toda semana com nosso teacher, pra aprimorar, aprender, praticar...
- Happy Hour Semanal. Toda semana temos um momento de descontração para nossos sanáticos.
- Sala de Descanso feita pra quem precisa relaxar e descansar um pouco ou pra aquela sonequinha depois do almoço.
- Equipamentos necessários para realizar o seu trabalho. Aqui você não precisa trazer os seus materiais. A Sanar ficará encarregada de entregar tudo que você precisa.
- Instrumentos Musicais para você mostrar seu talento pra gente.
-  Jogos para você relaxar. Temos aqui ping pong e xbox.

## Requisitos

**Obrigatórios:**
PROCURAMOS PESSOAS COM EXPERIÊNCIA ( E COM SEDE DE APRENDIZADO )…:

-    … de nível básico de TypeScript
-     ... de nível básico de GraphQL (Apollo ou Relay)
-     … em JavaScript (ES2015+)
-     ... de nível básico em React e seu ecossistema
-     ... de nível básico em desenvolvimento mobile (Android ou iOS)
-     ... de nível básico em GIT

## Contratação

- a combinar

## Nossa empresa

- A SANAR é uma HealthTech scale-up que existe para empoderar e dar superpoderes aos profissionais da saúde. Estamos divididos em duas grandes áreas de negócios: Medicina e Saúde.

## Como se candidatar

- [Clique aqui para se candidatar](https://jobs.kenoby.com/sanar/job/desenvolvedora-mobile-react-native-junior/5e55811fb9d937502929aafe)

**Comment by Thauan** [comment]
@BrendaCosta, boa tarde. O nível esta correto? No site da sanar só consta esta vaga para Pleno e Senior, é claro que a depender do conhecimento, é totalmente possível tentar, mas só ao teor de informação mesmo, eles tem interesse em Junior também?

**Comment by BrendaCosta** [comment]
Boa noite @Thauan, a gente só compartilha as informações da vaga, mas pelo tempo da vaga, possa ser que tenha encerrado
