### ISSUE TITLE
[GOOGLE CLOUD] [DOCKER] [REDES] [SEGURANÇA DE SISTEMAS] Analista de DevOps na [CUBOS]

### ISSUE THREAD

**Issue by devssa** [devssa/onde-codar-em-salvador#75]
## Local

Escritório- Salvador

## Benefícios

- Vale refeição ou alimentação;
- Plano de saúde ;
- Plano odontológico;
- Vale transporte;
- Aulas semanais multidisciplinares.

## Requisitos

**Obrigatórios:**
- Conhecer Google Cloud ou Amazon Web Services;
- Docker e Kubernetes;
- Nginx ou similar;
- Segurança de sistemas;
- Administração de Linux;
- Rede.

**Diferenciais:**
- Conhecimento de métodos ágeis;
- Experiência profissional com soluções digitais em startups.

## Contratação

Efetivo

## CUBOS

Somos uma desenvolvedora de softwares e, nos nossos projetos, utilizamos metodologias ágeis. Vamos muito além do desenvolvimento para fazer a diferença na vida das pessoas. Oferecemos um ambiente colaborativo, com uma galera massa trabalhando em busca da evolução contínua e prezando por fazer entregas foda.

﻿Buscamos pessoas fantásticas que se identifiquem com a nossa cultura e, principalmente, que queiram fazer e ser parte da nossa história.

## Como se candidatar

Link: https://cubos.gupy.io/jobs/36556

**Comment by rafaassism** [comment]
Olá!

Será que vocês poderiam fechar essa issue? Já fechamos essa vaga!

Muito obrigada desde já :)
