### ISSUE TITLE
Front-end Developer na [TOPTAL]

### ISSUE THREAD

**Issue by devssa** [devssa/onde-codar-em-salvador#76]
## FRONT-END DEVELOPER

Providing a great web user experience is crucial to us, and we’re always looking for talented front-end web developers to help us reach the next level.

By joining our team, you’ll get the opportunity to work on many of our projects with a team of highly skilled front-end experts from around the world. At Toptal, we push the boundaries of web interfaces every single day, and we’d love for you to help us take this even further. The bulk of the work we do is pure front-end development, but some back-end skills will help you.

We don’t cut corners, and we don’t make compromises—we create beautifully designed web apps that are polished, fast, well-tested, and a joy to use.

We are remote-only, have no office, and fully embrace a flexible work-life balance. All communication and resumes must be submitted in English.

**Responsibilities**

- Translate designs into code.
- Design, build, and maintain efficient, reusable, and reliable JavaScript and TypeScript code.
- Build cross-browser solutions optimized for a wide range of devices.
- Cover your code with tests and perform manual testing of your features.
- Review the work of your colleagues.
- As a true team player, you continuously improve your team’s processes, brainstorm ideas, and communicate your status and progress.
- Mentor other people, provide feedback, and continuously improve yourself.

## Local

REMOTO

## Requisitos

**Obrigatórios:**
- Have 5+ years of front-end web development experience—preference given to candidates who have experience with large applications of some scale.

- Be proficient in JavaScript, CSS3, and HTML5 is a must. Experience with React, Backbone, TypeScript is preferred.

- Have experience with responsive designs.

- Have experience developing within a web framework for backend—Ruby on Rails is a plus.

- Consider multiple quality dimensions like user impact, failure tolerance, code maintenance, implementation time, security breaches, and performance.

- Be genuinely interested in technology and love to try new things.

- Solve complex problems but also consider multiple solutions, weigh them, and decide on the best course of action.

- Thrive on providing and receiving honest but always constructive feedback.

## TOPTAL

Toptal is a global network of top talent in business, design, and technology that enables companies to scale their teams, on-demand. With $100+ million in annual revenue and triple-digit growth, Toptal is the largest fully distributed workforce in the world.

We take the best elements of virtual teams and combine them with a support structure that encourages innovation, social interaction, and fun (see this video from The Huffington Post). We see no borders, move at a fast pace, and are never afraid to break the mold.

## Como se candidatar

https://www.toptal.com/careers/front-end-developer

**Comment by m4risU** [comment]
TOPTOTAL -> TOPTAL ?

**Comment by devssa** [comment]
@m4risU fixed, tnkz
