### ISSUE TITLE
[TI] [SALVADOR] [PCD] Analista de TI (exclusivo para pessoas com deficiência - PCD) na [SOLUTIS]

### ISSUE THREAD

**Issue by lizvidotti91** [devssa/onde-codar-em-salvador#799]
## Descrição da vaga

- Buscamos profissionais antenados e flexíveis.
- Para essa oportunidade precisamos de um Analista de TI (PCD), que seja antenado, proativo, que goste de buscar e dividir conhecimentos.
- Flexibilidade trabalho remoto

RESPONSABILIDADES E ATRIBUIÇÕES
- Esse profissional atuará com:
- Desenvolvimento ou Suporte
- Java, .net ou help desk

## Local

- Salvador 

## Benefícios

- Informações diretamente com responsável/recrutador da vaga.

## Requisitos

**Obrigatórios:**
- Mindset focado em construir soluções;
- Capacidade de aprender com experiências de outros como também compartilhar suas próprias experiências;
- Ser apaixonado por tecnologia;
- Comprometimento em um ambiente voltado a entregas de alta colaboração.

## Contratação

- a combinar

## Nossa empresa

- Somos apaixonados por tecnologia e esse valor está presente em nossas ações e proposta de trabalho. Ambiente descontraído e criativo, horário flexível, possibilidade de trabalho home office, eventos e programas internos com games... Isso faz parte do nosso dia-a-dia.
- Engajamento, busca intensa por conhecimento, empatia e criatividade são a nossa receita para cultivar e colher, sempre, o melhor resultado tecnológico.
- Essa é a Solutis, flexível, acolhedora, inquieta, amante da tecnologia e de tudo que ela nos proporciona de mais incrível.
- Venha fazer parte do nosso time!

## Como se candidatar

- [Clique aqui para se candidatar](https://solutis.gupy.io/jobs/144398?jobBoardSource=gupy_public_page)

**Comment by YuLaFreitas** [comment]
Sou pcd, e dev Java, com quem posso entrar em contato?

**Comment by lizvidotti91** [comment]
Oi, @YuLaFreitas ! No final do post, tem um link em azul escrito "Clique aqui para se candidatar". Você vai ser direcionado pro anúncio da vaga, onde tem o link pra inscrição do processo seletivo da empresa
