### ISSUE TITLE
[BACKEND] [NODE] [JUNIOR] Desenvolvedor(a) Back-end/Node Júnior na [OCEANTEK]

### ISSUE THREAD

**Issue by lizvidotti91** [devssa/onde-codar-em-salvador#857]
## Descrição da vaga

- Uma pessoa curiosa e pró-ativa, que sabe perceber oportunidades de contribuição para o time. Ágil,
comprometida e com facilidade para lidar com mudanças porque irá atuar em diversos domínios de
negócios diferentes, e que não esquece de se divertir no processo. Que queira crescer. A cultura no
negócio é e sempre será um formato colaborativo onde todos crescem juntos.
- Estamos buscando profissionais com proatividade com bom relacionamento interpessoal. O(a) desenvolvedor(a) atuará no desenvolvimento de apps para empresas e startups.

## Local

- Remoto
- Empresa com sede em São Paulo, iniciando a implantação de time de desenvolvimento em Salvador.

## Benefícios

- Informações diretamente com o responsável/ recrutador da vaga.

## Requisitos

**Obrigatórios:**
- Conhecimentos: Javascript, NodeJs, Mysql / MongoDB;
- Bibliotecas: NPM, Sequelize, JOI;
- Criar código de boa qualidade a partir de designs e wireframes;
- Habilidade na comunicação verbal e escrita;
- Habilidade de programar e testar projetos de sistemas executados;
- Conhecimento em MVC;
- Ter preocupação com a qualidade de código, boas práticas, produtividade e trabalho em equipe;
- Atuar com controle de versão distribuído (Git).

**Desejáveis:**
- Experiência com integração com APIs RESTful e/ou webservices;
- Conhecimentos: OneSignal, Firebase, APIs do Google, APIs de redes sociais.

## Contratação

- a combinar

## Nossa empresa

- Fundada em 2012, a Oceantek surgiu para atender as demandas de soluções criativas desenvolvidas com tecnologias de ponta para suportar demandas de seus clientes ( sensores de movimento, sensores de monitoramento dos olhos, sensores de dispositivos mobile, IOT, motion design… ).
- Com o crescimento das plataformas mobile e fortalecimento de nossas relações com os clientes, novas soluções começaram a se destacar na carteira de produtos. A cultura de tornar a experiência simples, objetiva e fluída permitiu a criação de aplicações com alta penetração e fidelização.
- O foco hoje está em desenvolvimento de soluções tecnológicas customizadas e oferecer aos clientes soluções empresariais modernas e inovadoras. Comprometimento com ética, responsabilidade e transparência, em entender o objetivo e entregar soluções que se diferenciam da concorrência e desenvolvam o negócio dos clientes são sempre a prioridade da Oceantek.

## Como se candidatar

- [Clique aqui para se candidatar](https://trampos.co/oportunidades/161361-desenvolvedor-jr-backend-node)

**Comment by devdbreno** [comment]
A vaga ainda está ativa?

**Comment by lizvidotti91** [comment]
Olá, @devdbreno! Você pode clicar no link que está no final da postagem. Ela vai te direcionar para a página de cadastro da empresa, se ela ainda estiver em aberto
