### ISSUE TITLE
Desenvolvedor UNITY3D na [SOTEROTECH]

### ISSUE THREAD

**Issue by devssa** [devssa/onde-codar-em-salvador#92]
## Desenvolvedor UNITY3D

Desenvolver soluções atráves de Sistemas Web, Aplicativos Móveis, Jogos, Realidade Aumentada, Simuladores, dentre outros.

## Local

Lauro de Freitas - Ba

## Benefícios

- Horário Flexível
- Ambiente de trbaalho descontraído
- Vale Refeição
- Vale Transporte

## Requisitos

**Obrigatórios:**
- Unity3D
- C#
 - GIT
- WebGL

**Diferenciais:**
- XP DEV WEB
- Javascript
- XP TESTES
- Otimização e performance
- Metodologia ágil 

## Contratação

CLT(Efetivo)

## SOTERO TECH

Somos uma empresa brasileira de tecnologia digital e estamos localizados na região metropolitana de Salvador, na Bahia.

Realizamos trabalhos de destaque em pesquisa, concepção, coordenação e desenvolvimento de projetos nas áreas de Marketing, Comunicação, Tecnologia e Arte Digital, combinando inovação e praticidade na criação dos nossos projetos. Focada no atendimento das necessidades dos clientes, a Sotero Tech busca o que há de melhor em tecnologia no mercado mundial, visando agregar valor aos serviços e produtos, além de atrair e conquistar o público consumidor.

Desenvolvemos soluções atráves de Sistemas Web, Aplicativos Móveis, Jogos, Realidade Aumentada, Simuladores, dentre outros.

## Como se candidatar

Se encaixa no perfil? Envie seu CV, pretensão salarial e portfólio/Github com o assunto [VAGA UNITY3D] para selecao@soterotech.com.br

**Comment by fonxsirax** [comment]
Meu sonho essa vaga 
kkkkkk

**Comment by fxcosta** [comment]
@fonxsirax então se joga! Estamos aguardando teu e-mail!

**Comment by fxcosta** [comment]
@devssa obrigado por compartilhar a vaga, só uma correção, o local de trabalho é em Lauro de Freitas - BA. Obrigado!

**Comment by devssa** [comment]
@fxcosta corrigido, perdão pela demora
