### ISSUE TITLE
Analista de Sistemas na [REDE BAHIA]

### ISSUE THREAD

**Issue by devssa** [devssa/onde-codar-em-salvador#96]
## ANALISTA DE SISTEMAS

Rede Bahia Contrata Profissional com Ensino Superior Completo em Análise de Sistemas ou Áreas Afins

## Local

Federação - Salvador, BA

## Benefícios

- Assistencia Médica
- Assistencia Odontológica
- Participação nos Lucros
- Participação nos Resultados
- Refeitório na Empresa

## Requisitos

**Obrigatórios:**
- Desenvolvimento de Software
- Programação WEB
- C#
- SQL
- SCRUM
- Arquitetura de Software
- POO

## Contratação

CLT(Efetivo)

## Rede Bahia

TV Bahia é uma emissora de televisão brasileira sediada em Salvador, capital do estado da Bahia. Opera no canal 11 e é afiliada à Rede Globo. É a cabeça-de-rede da Rede Bahia de Televisão, que por sua vez pertence ao conglomerado Rede Bahia, o maior grupo de comunicação do Norte e Nordeste.

## Como se candidatar

Por favor envie um email para rh.talentos@redebahia.com.br com seu CV anexado

**Comment by yurisampaiosantos** [comment]
Boa, o e-mail informado não esta correto, poderia validar.
